#!/usr/bin/env php
<?php
chdir(dirname(__FILE__));
date_default_timezone_set('America/Chicago');

// Define path to application directory
defined('APPLICATION_PATH')
    || define('APPLICATION_PATH', realpath(dirname(__FILE__)));

// Define application environment
defined('APPLICATION_ENV')
    || define('APPLICATION_ENV', (getenv('APPLICATION_ENV') ?
    getenv('APPLICATION_ENV') : 'development'));

require_once('library/Doctrine.php');
spl_autoload_register(array('Doctrine', 'autoload'));

$dsn = 'sqlite:///' . APPLICATION_PATH . '/data/' . APPLICATION_ENV . '.db';
Doctrine_Manager::connection($dsn, 'demo');

$paths = array(
    'models_path'           =>  APPLICATION_PATH . '/application/models',
    'migrations_path'       =>  APPLICATION_PATH . '/doctrine/migrations',
    'yaml_schema_path'      =>  APPLICATION_PATH . '/doctrine/schema',
    'data_fixtures_path'    =>  APPLICATION_PATH . '/doctrine/data/fixtures',
    'sql_path'              =>  APPLICATION_PATH . '/doctrine/data/sql',
);

$cli = new Doctrine_Cli($paths);
$cli->run($_SERVER['argv']);
