<?php Zend_Dojo_View_Helper_Dojo::setUseDeclarative(); ?>

<span dojoType="dojo.data.ItemFileWriteStore" jsId="worklogStore" url="/index/list"></span>

<table id="dojo_worklogs" dojoType="dojox.grid.DataGrid" store="worklogStore" clientSort="true" query="{id: '*'}">
    <thead>
        <tr>
            <th width="10%" field="id">Id</th>

            <th width="90%" field="name">Name</th>

        </tr>
    </thead>
</table>

