<?php $dijitId = 'layout';

    $dijitParams = array( 'design' => 'headline',);

    $dijitAttribs = array(); ?>

<?php $this->borderContainer()->captureStart($dijitId, $dijitParams,
    $dijitAttribs) ?>

<?php echo $this->render('_header.phtml') ?>

<?php echo $this->render('_left.phtml') ?>

<?php echo $this->render('_main.phtml') ?>

<?php echo $this->render('_footer.phtml') ?>

<?php echo $this->borderContainer()->captureEnd($dijitId) ?>

